name: Terraform Deployment Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"  # Adjust the version as needed

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Specify the directory

    - name: Configure AWS credentials for Terraform
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform  # Specify the directory

    - name: Terraform destroy
      run: terraform destroy -auto-approve
      working-directory: ./terraform  # Specify the directory
