name: Terraform Deployment Workflow

on:
 workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"  # You can adjust the version as needed

    # Install Terraform dependencies (tflint and checkov)
    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Install Checkov
      run: |
        pip install checkov

    # Run Terraform fmt to ensure the code is properly formatted
    - name: Run Terraform fmt
      run: terraform fmt -check -diff

    # Run Terraform validate to ensure the configuration is valid
    - name: Run Terraform validate
      run: terraform validate

    # Run tflint using custom configurations
    - name: Run tflint with custom config
      run: tflint --config .tflint.hcl

    # Run Checkov to scan for security misconfigurations
    - name: Run Checkov
      run: checkov -d .

    # Set up AWS credentials using OIDC authentication (configure AWS CLI with your IAM role)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/OIDC-GitHub  # Replace with your actual role ARN
        role-session-name: github-actions-session
        aws-region: us-east-1  # Adjust to your AWS region

    # Initialize Terraform (this will download the provider and modules)
    - name: Terraform Init
      run: terraform init

    # Run Terraform Plan to see what changes will be applied
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Apply the Terraform changes (requires approval if you're using 'auto-approve')
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Output the API URL (if relevant)
    - name: Output API URL
      run: echo "Deployed API URL: $(terraform output -raw api_url)"
