name: Terraform Deployment Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"  # Adjust the version as needed

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Specify the directory

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Install Checkov
      run: |
        pip install checkov

    - name: Verify Checkov Installation
      run: checkov --version

    - name: Run Terraform fmt
      run: terraform fmt 
      working-directory: ./terraform  # Specify the directory

    - name: Run Terraform validate
      run: terraform validate
      working-directory: ./terraform  # Specify the directory

    - name: Install tflint AWS plugin
      run: |
        mkdir -p ~/.tflint.d/plugins
        curl -L https://github.com/terraform-linters/tflint-ruleset-aws/releases/latest/download/tflint-ruleset-aws_linux_amd64.zip -o /tmp/tflint-ruleset-aws.zip
        unzip /tmp/tflint-ruleset-aws.zip -d ~/.tflint.d/plugins

    - name: Initialize tflint plugins
      run: tflint --init
      working-directory: ./terraform  # Specify the directory

    - name: List tflint plugins
      run: ls -la ~/.tflint.d/plugins

    - name: Run tflint with custom config
      run: |
        TFLINT_LOG=debug tflint --config .tflint.hcl
      working-directory: ./terraform  # Specify the directory

    - name: Run Checkov
      run: checkov -d . --output json --output-file checkov_results.json
      working-directory: ./terraform  # Specify the directory
      continue-on-error: true  # Continue even if Checkov fails

    - name: Upload Checkov Results
      uses: actions/upload-artifact@v4.6.1
      with:
        name: checkov-results
        path: ./terraform/checkov_results.json

    - name: Configure AWS credentials for Terraform
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform  # Specify the directory

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Specify the directory
