name: Terraform Deployment Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"  # Adjust the version as needed

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Specify the directory

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Install Checkov
      run: |
        pip install checkov

    - name: Run Terraform fmt
      run: terraform fmt 
      working-directory: ./terraform  # Specify the directory

    - name: Run Terraform validate
      run: terraform validate
      working-directory: ./terraform  # Specify the directory

    - name: Initialize tflint plugins
      run: tflint --init
      working-directory: ./terraform  # Specify the directory

    - name: Run tflint with custom config
      run: tflint --config .tflint.hcl
      working-directory: ./terraform  # Specify the directory

    - name: Run Checkov
      run: checkov -d .
      working-directory: ./terraform  # Specify the directory

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::510278866235:role/OIDC-GitHub  # Replace with your actual role ARN
        role-session-name: github-actions-session
        aws-region: us-east-1  # Adjust to your AWS region (e.g., us-west-2, eu-west-1, etc.)

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform  # Specify the directory

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Specify the directory
